export function dayTabs() {
    const dayTabsContainer = document.querySelector('.day-tabs-container')
    for (let i = 0; i < 7; i++) {
        const dayTab = document.createElement('div')
        dayTab.classList.add('day-tab')
        dayTab.classList.add('inactive-tab')
        dayTab.setAttribute('id', `day${i}`)
        dayTabsContainer.appendChild(dayTab)

            const dateContainer = document.createElement('div')
            dateContainer.classList.add('date-container')
            dayTab.appendChild(dateContainer)
                const date = document.createElement('p')
                date.classList.add('date')
                dateContainer.appendChild(date)

            const weatherContainer = document.createElement('div')
            weatherContainer.classList.add('weather')
            dayTab.appendChild(weatherContainer)
                const weatherIcon = document.createElement('img')
                weatherIcon.classList.add('weather-icon')
                weatherContainer.appendChild(weatherIcon)
                const weatherText = document.createElement('p')
                weatherText.classList.add('weather-text')
                weatherContainer.appendChild(weatherText)

            const tempRangeContainer = document.createElement('div')
            tempRangeContainer.classList.add('temp-range')
            dayTab.appendChild(tempRangeContainer)
                const minTempIcon = document.createElement('i')
                minTempIcon.classList.add('fa-solid')
                minTempIcon.classList.add('fa-temperature-arrow-down')
                tempRangeContainer.appendChild(minTempIcon)
                const minTemp = document.createElement('p')
                minTemp.classList.add('min-temp')
                tempRangeContainer.appendChild(minTemp)
                const maxTempIcon = document.createElement('i')
                maxTempIcon.classList.add('fa-solid')
                maxTempIcon.classList.add('fa-temperature-arrow-up')
                tempRangeContainer.appendChild(maxTempIcon)
                const maxTemp = document.createElement('p')
                maxTemp.classList.add('max-temp')
                tempRangeContainer.appendChild(maxTemp)

            const currentTempContainer = document.createElement('div')
            currentTempContainer.classList.add('current-temp-container')
            dayTab.appendChild(currentTempContainer)
                const currentTemp = document.createElement('p')
                currentTemp.classList.add('current-temp')
                currentTempContainer.appendChild(currentTemp)
                const feelsLike = document.createElement('p')
                feelsLike.classList.add('feels-like')
                currentTempContainer.appendChild(feelsLike)

            const precipContainer = document.createElement('div')
            precipContainer.classList.add('precip-container')
            dayTab.appendChild(precipContainer)
                const precipIcon = document.createElement('i')
                precipIcon.classList.add('fa-solid')
                precipIcon.classList.add('fa-cloud-rain')
                precipContainer.appendChild(precipIcon)
                const precipText = document.createElement('p')
                precipText.classList.add('preciptation')
                precipContainer.appendChild(precipText)

            const windContainer = document.createElement('div')
            windContainer.classList.add('wind-container')
            dayTab.appendChild(windContainer)
                const windIcon = document.createElement('i')
                windIcon.classList.add('fa-solid')
                windIcon.classList.add('fa-wind')
                windContainer.appendChild(windIcon)
                const windText = document.createElement('p')
                windText.classList.add('wind-speed-tab')
                windContainer.appendChild(windText)

            const uvContainer = document.createElement('div')
            uvContainer.classList.add('uv-container')
            dayTab.appendChild(uvContainer)
                const uvIcon = document.createElement('i')
                uvIcon.classList.add('fa-solid')
                uvIcon.classList.add('fa-sun')
                uvContainer.appendChild(uvIcon)
                const uvText = document.createElement('p')
                uvText.classList.add('uv-index')
                uvContainer.appendChild(uvText)
            
            const cloudContainer = document.createElement('div')
            cloudContainer.classList.add('cloud-coverage-container')
            dayTab.appendChild(cloudContainer)
                const cloudIcon = document.createElement('i')
                cloudIcon.classList.add('fa-solid')
                cloudIcon.classList.add('fa-cloud')
                cloudContainer.appendChild(cloudIcon)
                const cloudText = document.createElement('p')
                cloudText.classList.add('cloud-coverage')
                cloudContainer.appendChild(cloudText)

            const sunriseContainer = document.createElement('div')
            sunriseContainer.classList.add('sunrise-container')
            dayTab.appendChild(sunriseContainer)
                const sunrise = document.createElement('p')
                sunrise.classList.add('sunrise')
                sunriseContainer.appendChild(sunrise)
              
            const sunsetContainer = document.createElement('div')
            sunsetContainer.classList.add('sunset-container')
            dayTab.appendChild(sunsetContainer)
                const sunset = document.createElement('p')
                sunset.classList.add('sunset')
                sunsetContainer.appendChild(sunset)

            const descriptionContainer = document.createElement('div')
            descriptionContainer.classList.add('description-container')
            dayTab.appendChild(descriptionContainer)
                const description = document.createElement('p')
                description.classList.add('description')
                descriptionContainer.appendChild(description)
    }
}